CREATE TABLE `declaration_articles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`declarationId` int NOT NULL,
	`productId` int NOT NULL,
	`isPrimary` boolean NOT NULL DEFAULT false,
	`snapshotProductName` varchar(512),
	`snapshotArticleNumber` varchar(128),
	`snapshotEan` varchar(64),
	`snapshotBrand` varchar(255),
	`snapshotAgeGrading` varchar(128),
	`imageUrl` text,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `declaration_articles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `declaration_status_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`declarationId` int NOT NULL,
	`action` varchar(64) NOT NULL,
	`fromStatus` enum('draft','sent','manufacturer_review','signed','ai_validated','archived'),
	`toStatus` enum('draft','sent','manufacturer_review','signed','ai_validated','archived'),
	`performedByUserId` int,
	`performedByName` varchar(255),
	`note` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `declaration_status_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `declarations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL DEFAULT 1,
	`productId` int NOT NULL,
	`supplierId` int NOT NULL,
	`docNumber` varchar(64) NOT NULL,
	`version` int NOT NULL DEFAULT 1,
	`status` enum('draft','sent','manufacturer_review','signed','ai_validated','archived') NOT NULL DEFAULT 'draft',
	`effectiveProductName` varchar(512),
	`effectiveAgeGrading` varchar(128),
	`euDirectives` json DEFAULT ('[]'),
	`chRegulations` json DEFAULT ('[]'),
	`standards` json DEFAULT ('[]'),
	`testReportRef` varchar(512),
	`notifiedBody` varchar(255),
	`chConformityBody` varchar(255),
	`issuedDate` timestamp,
	`issuedPlace` varchar(255),
	`manufacturerContactName` varchar(255),
	`manufacturerContactEmail` varchar(320),
	`portalToken` varchar(128),
	`portalTokenExpiresAt` timestamp,
	`sentAt` timestamp,
	`signedAt` timestamp,
	`signedByName` varchar(255),
	`signedByPosition` varchar(255),
	`signatureMethod` enum('manual_upload','esignature') DEFAULT 'manual_upload',
	`signedPdfUrl` text,
	`signedPdfKey` varchar(512),
	`draftPdfUrl` text,
	`draftPdfKey` varchar(512),
	`aiValidationPassed` boolean,
	`aiValidationResult` json,
	`aiValidationSummary` text,
	`aiValidatedAt` timestamp,
	`archivedDocumentId` int,
	`archivedAt` timestamp,
	`createdByUserId` int NOT NULL,
	`updatedByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `declarations_id` PRIMARY KEY(`id`),
	CONSTRAINT `declarations_docNumber_unique` UNIQUE(`docNumber`),
	CONSTRAINT `declarations_portalToken_unique` UNIQUE(`portalToken`)
);
