CREATE TABLE IF NOT EXISTS `incident_assessments` (
  `id` int AUTO_INCREMENT NOT NULL,
  `incidentId` int NOT NULL,
  `assessedByUserId` int NOT NULL,
  `assessmentType` enum('initial','technical','legal','final') DEFAULT 'initial',
  `riskLevel` enum('critical','high','medium','low','none') NOT NULL,
  `recallRecommended` boolean NOT NULL DEFAULT false,
  `recallScope` enum('none','targeted','voluntary','mandatory') DEFAULT 'none',
  `assessmentText` text NOT NULL,
  `regulatoryObligation` boolean DEFAULT false,
  `regulatoryDeadline` timestamp NULL,
  `regulatoryBasis` text,
  `requiredDocuments` json,
  `internalNotes` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `incident_assessments_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `incident_evidences` (
  `id` int AUTO_INCREMENT NOT NULL,
  `incidentId` int NOT NULL,
  `evidenceType` enum('photo','customer_statement','internal_report','medical_report','authority_document','product_sample','video','other') NOT NULL,
  `fileName` varchar(512) NOT NULL,
  `fileUrl` text NOT NULL,
  `fileKey` varchar(512) NOT NULL,
  `mimeType` varchar(128),
  `fileSizeBytes` int,
  `description` text,
  `sourceType` enum('upload','link','text') DEFAULT 'upload',
  `textContent` text,
  `uploadedByUserId` int,
  `uploadedAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `incident_evidences_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `incident_recalls` (
  `id` int AUTO_INCREMENT NOT NULL,
  `incidentId` int NOT NULL,
  `recallType` enum('voluntary','mandatory','targeted') NOT NULL,
  `recallScope` text NOT NULL,
  `status` enum('planned','announced','active','completed','cancelled') NOT NULL DEFAULT 'planned',
  `announcementText` text,
  `affectedUnitsCount` int,
  `recallStartDate` timestamp NULL,
  `recallEndDate` timestamp NULL,
  `authorityNotified` boolean DEFAULT false,
  `authorityNotifiedAt` timestamp NULL,
  `authorityNames` json,
  `publicAnnouncement` boolean DEFAULT false,
  `publicAnnouncementUrl` text,
  `pressReleaseUrl` text,
  `remediationAction` enum('refund','replacement','repair','disposal','other'),
  `remediationInstructions` text,
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `incident_recalls_id` PRIMARY KEY(`id`),
  CONSTRAINT `incident_recalls_incidentId_unique` UNIQUE(`incidentId`)
);

CREATE TABLE IF NOT EXISTS `incident_timeline` (
  `id` int AUTO_INCREMENT NOT NULL,
  `incidentId` int NOT NULL,
  `action` varchar(128) NOT NULL,
  `performedByUserId` int,
  `performedByName` varchar(255),
  `note` text,
  `metadata` json,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `incident_timeline_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `incidents` (
  `id` int AUTO_INCREMENT NOT NULL,
  `tenantId` int NOT NULL DEFAULT 1,
  `productId` int,
  `incidentType` enum('personal_injury','property_damage','near_miss','product_defect','regulatory_complaint','customer_complaint','other') NOT NULL,
  `severity` enum('critical','high','medium','low') NOT NULL,
  `status` enum('open','under_review','assessed','recall_initiated','recall_completed','closed','archived') NOT NULL DEFAULT 'open',
  `title` varchar(512) NOT NULL,
  `description` text NOT NULL,
  `reportedByName` varchar(255),
  `reportedByEmail` varchar(320),
  `reportedByType` enum('customer','supplier','internal','authority','other') DEFAULT 'customer',
  `reportedAt` timestamp NOT NULL,
  `affectedVersions` json,
  `affectedBatchNumbers` json,
  `affectedUnitsEstimate` int,
  `injuryDescription` text,
  `injuredPersonAge` int,
  `injuredPersonType` enum('child','adult','unknown'),
  `medicalTreatmentRequired` boolean DEFAULT false,
  `hospitalisation` boolean DEFAULT false,
  `reportedToAuthority` boolean DEFAULT false,
  `authorityName` varchar(255),
  `authorityReportDate` timestamp NULL,
  `authorityReferenceNumber` varchar(128),
  `assignedToUserId` int,
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `incidents_id` PRIMARY KEY(`id`)
);
