CREATE TABLE `incident_cost_centers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`incidentId` int NOT NULL,
	`tenantId` int NOT NULL DEFAULT 1,
	`costCenterCode` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'CHF',
	`status` enum('open','on_hold','closed') NOT NULL DEFAULT 'open',
	`insurerName` varchar(255),
	`insurerClaimReference` varchar(128),
	`notes` text,
	`createdByUserId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `incident_cost_centers_id` PRIMARY KEY(`id`),
	CONSTRAINT `incident_cost_centers_incidentId_unique` UNIQUE(`incidentId`),
	CONSTRAINT `incident_cost_centers_costCenterCode_unique` UNIQUE(`costCenterCode`)
);
--> statement-breakpoint
CREATE TABLE `incident_cost_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`incidentId` int NOT NULL,
	`costCenterId` int NOT NULL,
	`tenantId` int NOT NULL DEFAULT 1,
	`category` enum('internal_time','logistics','legal','expert_opinion','laboratory','authority_fees','customer_remediation','travel','communication','other') NOT NULL,
	`description` text NOT NULL,
	`incurredAt` timestamp NOT NULL,
	`counterparty` varchar(255),
	`invoiceNumber` varchar(128),
	`hours` decimal(10,2),
	`hourlyRate` decimal(12,2),
	`amountNet` decimal(14,2) NOT NULL,
	`vatAmount` decimal(14,2) NOT NULL DEFAULT '0.00',
	`amountGross` decimal(14,2) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'CHF',
	`status` enum('planned','incurred','invoiced','paid','submitted_to_insurer','partially_reimbursed','reimbursed','disputed','voided') NOT NULL DEFAULT 'incurred',
	`insurerReference` varchar(128),
	`receiptFileName` varchar(512),
	`receiptFileUrl` text,
	`receiptFileKey` varchar(512),
	`receiptMimeType` varchar(128),
	`receiptFileSizeBytes` int,
	`voidReason` text,
	`createdByUserId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `incident_cost_entries_id` PRIMARY KEY(`id`)
);
